raw_data_path: "data/raw/hour.csv"
train_data_path: "data/interim/train.csv"
test_data_path: "data/interim/test.csv"
output_model_path: "src/model/model.pkl"
model_hparams_path: "conf/model_hparams/model_hparams.yaml"
metrics_path: "src/model/metrics.json"
output_data_path: "src/model/predictions.csv"